### ISSUE TITLE
Alpine based docker image does not properly run in Kubernetes

### ISSUE THREAD

**Issue by McToel** [derhuerst/db-rest#41] opened 2024-01-23 19:17 UTC
I am running an instance of db-rest:6 for some time in kubernetes. A few hours ago, it stopped working (Error: `reason: getaddrinfo EAI_AGAIN`). While I have no idea why it worked before, I found out that the problem seems to be, that db-rest:6 is based on Alpine which seems to have known problems to resolve DNS in kubernetes ([see here](https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes))

I was able to resolve the issue by building a new image based of node-18-bullseye.

Probably I am the only one having this issue, so I don't know whether it's worth fixing it.

**Comment by derhuerst** [comment] 2024-01-25 12:43
I'm not sure this is the actual cause of the `EAI_AGAIN` error. After all,

- the StackOverflow post linked by you refers to *huge* DNS responses.
- supposedly, it is fixed in the latest Alpine versions.
- there are many other possible error sources, e.g. caching.

What does "it stopped working" mean? What exactly fails?

**Comment by McToel** [comment] 2024-01-25 13:20
It stopped working means every single response fails with the same error described above. Restarting pods, the cluster, the kubernetes dns and so on did not help.

I've gone through many debugging steps (following [this).](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/). Using the dnsutils Pod describe in the guide everything works fine, if I instead use the node-18-alpine image, nslookup fails with NXDOMAIN. It might be fixed in other alpine images, however in the base image of your Dockerfile it is not.

My current fix is as simple as:
```Dockerfile
FROM derhuerst/db-rest:6 as builder

FROM node:18-bullseye
WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

ENV HOSTNAME example.com
ENV PORT 3000

CMD ["node", "index.js"]
```

Maybe there is a way to configure it so that it works with the node-18-alpine image, maybe it is fixed in a node-20-apline image, but I did not want to run db-rest with an maybe unsupported node version.

**Comment by derhuerst** [comment] 2024-01-25 13:58
Can you check if the issue is gone with the latest Docker image (built a few minutes ago)? I just triggered another CI run, so it should have more up-to-date base layers.

**Comment by McToel** [comment] 2024-01-25 14:07
I've tried, but it still gives me `** server can't find kubernetes.default: NXDOMAIN`. I don't think this has anything to do with JS dependencies.

**Comment by McToel** [comment] 2024-01-25 14:30
I did some more tests. While nslookup does not work as expected, wget (failed with `bad domain` before) does, and db-rest is running without errors.

**Comment by derhuerst** [comment] 2024-01-25 15:40
Could it be that you're resolving the API's domain with every single request, and that eventually their DNS server blocks requests?

**Comment by McToel** [comment] 2024-01-27 09:08
I don't know how to find out if that's what's happening, but tonight it broke again after running for two days, so maybe it is some kind of DNS caching issue. However, other containers running on the same cluster querying different APIs of DB don't have the same issue

**Comment by derhuerst** [comment] 2024-01-27 17:01
You could debug more by shelling into the container and using e.g. `dig` (which talks directly to the name servers when used with the `@<ns>` notation), `host` and `nslookup` to debug this. Some of these use the locally configured resolver, some of them don't, so this might be a debugging angle.

**Comment by McToel** [comment] 2024-01-30 14:35
Well, the problem is that I don't want to redeploy the official docker image, as it failed. And I don't have the time right now to build a second setup to test the failing pod. Maybe if I have time in March I will try to do some further debugging or if something breaks before that.

**Comment by derhuerst** [comment] 2024-01-31 12:40
> Well, the problem is that I don't want to redeploy the official docker image, as it failed.

You don't have to deploy something else I think. A simple `kubectl exec <db-rest-container>` should be enough.

Unfortunately, I can't help debug your Kubernetes network setup, and I don't want to switch away from Alpine Linux because of something that is not 100% confirmed to be caused by Alpine Linux.

If you have the time to provide more details about the error, don't hesitate to post here!

**Comment by derhuerst** [comment] 2024-02-20 15:47
To clarify again: I'll definitely consider adapting the `db-rest` Docker image if there is a confirmation that the network issues are indeed related to Alpine Linux (even if it's only in combination with Kubernetes).

Until then, I'll close this, as I'd like to keep an overview over more actionable tasks in my projects. Please don't hesitate to re-open the Issue if you have found out more!

**Closed as not planned by derhuerst** 2024-02-20 15:47 UTC
Labels: bug
