### ISSUE TITLE
allow customising the traveller's age (/journeys)

### ISSUE THREAD

**Issue by JannesT3011** [derhuerst/db-rest#29] opened 2023-03-02 09:50 UTC
Hi, it would be great if you can add the travelers age to this endpoint: https://v6.db.transport.rest/api/journeys

**Comment by derhuerst** [comment] 2023-03-02 10:04
this option specific to the DB HAFAS endpoint is currently [buried deep inside `hafas-client`](https://github.com/public-transport/hafas-client/blob/673eb4d6c778ce70e4d451d04bac68f418fd6fa9/p/db/index.js#L165) (which is used by `db-hafas`, which is used here in `db-rest`). it is missing from the documentation (& OpenAPI schema) because it is not added by [`mapRouteParsers()`](https://github.com/derhuerst/db-rest/blob/779e67886bbaf550d52ff6c6e826bd7a866cf851/api.js#L62).

a PR that adds this is very welcome!

**Comment by derhuerst** [comment] 2023-03-02 10:07
I just noticed this is a duplicate of https://github.com/derhuerst/db-rest/issues/25, closing this Issue in favour of it.

**Closed as completed by derhuerst** 2023-03-02 10:07 UTC
Labels: enhancement, help wanted
